SCREEN_WIDTH = 800
SCREEN_HEIGHT = 700
BLOCK_SIZE = 30

X = 0
Y = 1

NUM_ROWS = 20
NUM_COLUMNS = 10

PLAY_WIDTH = BLOCK_SIZE * NUM_COLUMNS
PLAY_HEIGHT = BLOCK_SIZE * NUM_ROWS
TOP_LEFT = ((SCREEN_WIDTH - PLAY_WIDTH) // 2, (SCREEN_HEIGHT - PLAY_HEIGHT))

NUM_ROWS = 20
NUM_COLUMNS = 10

LEFT_KEY = 0
RIGHT_KEY = 1
ROTATE_KEY = 2
DOWN_KEY = 3